### PR TITLE
factor loop-match pattern out of AssertAsync method impls

### PR DESCRIPTION
**Pull request by zseri**
Noticed this during the review of #62. I'm open for bikeshedding on the `assert_async_antipoll` name.

### CODE REVIEW

**Review by notgull — APPROVED** [review]
Looks good to me!

`assert_async_antipoll` is an odd name, in my opinion. I think it would be better if it was named `wrap_io` and was an associated method on `AssertAsync`.

**Comment by zseri** [comment]
I didn't want to make it an associated method because it's completely independent from the type parameter `<T>`

**Comment by zseri** [comment]
I renamed it to `assert_async_wrapio`.

**Review by notgull — APPROVED** [review]
I like the new name better.

**Pull request merged**
